app: sykepengesoknad-ikke-sendt-altinnvarsel
namespace: flex
team: flex
kafkaPool: nav-dev
db_tier: db-f1-micro
external-host:
  - pdl-api.dev-fss-pub.nais.io
  - tt02.altinn.no
azureTenant: trygdeetaten.no
env:
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  ALTINN_URL: https://tt02.altinn.no
  OVERSTYR_ORGNR: ja
