apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 300m
      memory: 600Mi
    requests:
      cpu: 200m
      memory: 500Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: sykepengesoknad-ikke-sendt-altinnvarsel-db
  accessPolicy:
    outbound:
      external:
      {{#each externalHosts as |url|}}
          - host: {{url}}
      {{/each}}
  kafka:
    pool: {{kafkaPool}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  leaderElection: true
  envFrom:
    - secret: altinn-serviceuser
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
